@IsTest
private class SubscriptionTriggerTest {

    @TestSetup
    private static void createTestData() {

    }

    @IsTest
    private static void testPreventionOfSubscriptionCreationForNonAvailableCars() {

    }

    @IsTest
    private static void testCarAssignmentForContractedSubscriptions() {

    }

    @IsTest
    private static void testUnblockingOfCarsForTerminatedSubscriptions() {

    }

}